name: Amber
version: 0.1
main: com.deaboy.amber.AmberPlugin
website: github.com/Deaboy/Amber
author: Deaboy
commands:
    amber:
        usage:
        description: Access basic Amber commands